export const driverRows = [
  {
    name: "Carl J.",
    market: "Houston",
    onTime: 94,
    miles: 2840,
    loads: 9,
    hos: 88,
    status: "active",
  },
  {
    name: "Mike R.",
    market: "DFW",
    onTime: 98,
    miles: 3120,
    loads: 11,
    hos: 92,
    status: "active",
  },
  {
    name: "Devon T.",
    market: "KC",
    onTime: 91,
    miles: 2680,
    loads: 8,
    hos: 95,
    status: "active",
  },
  {
    name: "Priya S.",
    market: "SoCal",
    onTime: 96,
    miles: 3340,
    loads: 12,
    hos: 89,
    status: "active",
  },
  {
    name: "James W.",
    market: "DFW",
    onTime: 82,
    miles: 1920,
    loads: 6,
    hos: 78,
    status: "warning",
  },
]
